"use client"

// ==== Styles ==== //
import "../styles/globals.css";
// ==== Components ==== //
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

// ==== Theme ==== //
import { ThemeProvider } from "next-themes";


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>My Portfolio</title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="description" content="Generated by create next app" />
      </head>
      <body className="dark:bg-columms_heading" >
        <ThemeProvider attribute="class">
          <Navbar />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
